
export const LOADING = 'LOADING';
export const ERROR = 'ERROR';
export const CLEANUP = "CLEANUP";
export const GOT_ITEMS = 'GOT_ITEMS';
export const GOT_ITEMS_INGREDIANTS = "GOT_ITEMS_INGREDIANTS";

export const FETCH_MENU_ITEM_REQUEST = "FETCH_MENU_ITEM_REQUEST";
export const FETCH_MENU_ITEM_SUCCESS = "FETCH_MENU_ITEM_SUCCESS";
export const FETCH_MENU_ITEM_FAILURE = "FETCH_MENU_ITEM_FAILURE";
