export const LOADING = "LOADING";
export const ERROR = "ERROR";
export const CLEANUP = "CLEANUP";
export const GOT_ITEMS = "GOT_ITEMS";
export const GOT_ITEMS_INGREDIANTS = "GOT_ITEMS_INGREDIANTS";

export const FETCH_MENU_ITEM_REQUEST = "FETCH_MENU_ITEM_REQUEST";
export const FETCH_MENU_ITEM_SUCCESS = "FETCH_MENU_ITEM_SUCCESS";
export const FETCH_MENU_ITEM_FAILURE = "FETCH_MENU_ITEM_FAILURE";

export const GET_EXTRA_ITEM_TOPPINGS_REQUEST =
  "GET_EXTRA_ITEM_TOPPINGS_REQUEST";
export const GET_EXTRA_ITEM_TOPPINGS_SUCCESS =
  "GET_EXTRA_ITEM_TOPPINGS_SUCCESS";
export const GET_EXTRA_ITEM_DRIZZLE_SUCCESS = "GET_EXTRA_ITEM_DRIZZLE_SUCCESS";
export const GET_EXTRA_ITEM_TOPPINGS_FAILURE =
  "GET_EXTRA_ITEM_TOPPINGS_FAILURE";

export const POSTED_TOPPINGS = "POSTED_TOPPINGS";
export const GET_REVIEW_SUCCESS = "GET_REVIEW_SUCCESS";
export const GET_SUPPORT_SUCCESS = "GET_SUPPORT_SUCCESS";
export const GET_TABLE_RESERVATION_SUCCESS = "GET_TABLE_RESERVATION_SUCCESS";
export const GET_ALL_OUTLET_SUCCESS = "GET_ALL_OUTLET_SUCCESS";
export const GET_OUTLET_TIME_SLOTS_SUCCESS = "GET_OUTLET_TIME_SLOTS_SUCCESS";
export const POST_OUTLET_TIME_SLOTS_SUCCESS = "POST_OUTLET_TIME_SLOTS_SUCCESS";